services:
  boomapi:
    image: vicenteyu105/boomapi:latest
    container_name: boomapi
    ports:
      - "8080:8080"
    volumes:
      - ./my-mocks:/app/data
      - ./my-logs:/app/logs
    restart: always